"""Pytest-compatible fuzz runner.

Drives `differential.run_pair` for N seeds per (branch, property)
pair, optionally piping the Aiken-mappable inputs to a subprocess that
runs `aiken check --match-tests fuzz_*` against generated test source.

Two operating modes:
  * `fuzz_pair`           — Tier 1 only. Pure Python; fast.
  * `fuzz_pair_with_aiken` — Tier 1 + Tier 2 (subprocess to aiken).

Tier-2 is opt-in because subprocess-to-aiken is slow (~3-5s per call).
The Tier-2 path also requires `aiken` to be on PATH and the contracts
project to compile cleanly.
"""

from __future__ import annotations

import dataclasses
import os
import subprocess
import sys
from pathlib import Path
from typing import Iterable

from .concrete_generator import BRANCH_GENERATORS
from .differential import (
    AIKEN_MAPPED_PAIRS,
    BRANCH_PROPERTY_PAIRS,
    DifferentialResult,
    run_pair,
    write_fixture,
)


CONTRACTS_DIR = Path("D:/aegis/contracts")
DEFAULT_FIXTURE_OUT = (
    Path(__file__).resolve().parent / "generated_fixtures"
)


# ---------------------------------------------------------------------------
# Aiken-side test source generation
# ---------------------------------------------------------------------------


# A small Aiken module that holds N generated test functions, one per
# fuzz sample. Each test function calls the mapped helper with the
# concrete args and asserts the Python-predicted boolean.
AIKEN_MODULE_HEADER = """// AUTO-GENERATED by symbolic_executor.fuzz — DO NOT EDIT BY HAND.
// Regenerate with `pytest D:/aegis/redteam/symbolic_executor/fuzz/`.

use aegis/pool.{can_underwrite, can_withdraw}
use aegis/pricing.{is_premium_adequate}

"""


def _emit_aiken_test(
    idx: int, fn_name: str, args: tuple, expected: bool
) -> str:
    """Emit one Aiken `test` function for a fuzz sample."""
    args_str = ", ".join(str(a) for a in args)
    expected_str = "True" if expected else "False"
    return (
        f"test fuzz_{fn_name}_{idx:06d}() {{\n"
        f"  {fn_name}({args_str}) == {expected_str}\n"
        f"}}\n\n"
    )


def emit_aiken_test_module(samples: Iterable[tuple[str, tuple, bool]]) -> str:
    """Render a complete Aiken test module from a list of samples."""
    out = [AIKEN_MODULE_HEADER]
    for idx, (fn_name, args, expected) in enumerate(samples):
        out.append(_emit_aiken_test(idx, fn_name, args, expected))
    return "".join(out)


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


@dataclasses.dataclass
class FuzzReport:
    """Aggregate report for a fuzz_pair invocation."""

    branch: str
    property: str
    n_requested: int
    n_sampled: int
    n_holds: int
    n_violates: int
    n_unsampled: int
    disagreements: list[DifferentialResult]
    aiken_inputs: list[tuple[str, tuple, bool]]
    aiken_subprocess_result: dict | None = None

    @property
    def all_hold(self) -> bool:
        """Every sampled input had the property hold (no disagreement)."""
        return self.n_violates == 0


# ---------------------------------------------------------------------------
# Tier 1: Python concrete re-evaluation only
# ---------------------------------------------------------------------------


def fuzz_pair(
    branch: str,
    property_name: str,
    n: int,
    seed_base: int = 1,
    max_unsampled_retries: int = 10,
) -> FuzzReport:
    """Run N differential samples for (branch, property).

    Tier 1: Python concrete re-evaluation only. No Aiken subprocess.

    The function ALWAYS returns a report — it does NOT raise. Callers
    (pytest harnesses) inspect `.all_hold` to assert no disagreements.

    `max_unsampled_retries` controls how many alternative seeds to try
    when the diversity pins yield UNSAT (some branches like
    RemoveLiquidity require divisibility-friendly numbers).
    """
    sampled = 0
    holds = 0
    violates = 0
    unsampled = 0
    disagreements: list[DifferentialResult] = []
    aiken_inputs: list[tuple[str, tuple, bool]] = []

    for i in range(n):
        seed = seed_base * 10_000 + i
        res = run_pair(branch, property_name, seed)
        # Retry with a few alternative seeds if diversity pins
        # produced an UNSAT model (some branches' encoders are
        # constrained on integer-division divisibility).
        retries = 0
        while not res.sampled and retries < max_unsampled_retries:
            retries += 1
            res = run_pair(
                branch,
                property_name,
                seed + retries * 1_000_003,
            )
        if not res.sampled:
            unsampled += 1
            continue
        sampled += 1
        if res.concrete_holds:
            holds += 1
        else:
            violates += 1
            disagreements.append(res)
        if res.aiken_input is not None:
            aiken_inputs.append(res.aiken_input)

    return FuzzReport(
        branch=branch,
        property=property_name,
        n_requested=n,
        n_sampled=sampled,
        n_holds=holds,
        n_violates=violates,
        n_unsampled=unsampled,
        disagreements=disagreements,
        aiken_inputs=aiken_inputs,
    )


# ---------------------------------------------------------------------------
# Tier 2: also run inputs through `aiken check` subprocess
# ---------------------------------------------------------------------------


def _aiken_baseline_clean(contracts_dir: Path, timeout_s: int = 120) -> tuple[bool, str]:
    """Return (clean, reason). True iff `aiken check --skip-tests`
    succeeds on the contracts project as-is (no generated files).

    If the contracts project itself doesn't type-check, our generated
    fuzz module will inherit that failure and we can't tell whether
    OUR generated tests pass. Tier-2 must short-circuit to a skip in
    that case.
    """
    try:
        proc = subprocess.run(
            [
                "aiken",
                "check",
                str(contracts_dir),
                "--skip-tests",
                "--silent",
            ],
            capture_output=True,
            text=True,
            timeout=timeout_s,
        )
    except FileNotFoundError:
        return False, "aiken binary not on PATH"
    except subprocess.TimeoutExpired:
        return False, f"aiken baseline check timed out after {timeout_s}s"
    if proc.returncode != 0:
        # Trim stderr to first 200 chars for the skip reason.
        snippet = (proc.stderr or proc.stdout or "<no output>").strip()[:200]
        return False, (
            f"contracts project does not type-check (returncode "
            f"{proc.returncode}); snippet: {snippet}"
        )
    return True, ""


def _run_aiken(
    test_source: str,
    match_filter: str,
    contracts_dir: Path = CONTRACTS_DIR,
    timeout_s: int = 120,
) -> dict:
    """Write `test_source` to `contracts/lib/aegis/_fuzz_generated.ak`
    and run `aiken check -m <match_filter>`.

    Returns a dict {"ok": bool, "stdout": str, "stderr": str,
                    "returncode": int, "skipped_reason": Optional[str]}.

    Tier-2 is best-effort. If aiken isn't installed or the contracts
    project doesn't compile, we set ok=True and skipped_reason=<why>
    so the differential harness can still report Tier-1 results.
    """
    if not contracts_dir.exists():
        return {
            "ok": True,
            "skipped_reason": f"contracts dir missing: {contracts_dir}",
            "stdout": "",
            "stderr": "",
            "returncode": 0,
        }

    baseline_ok, baseline_reason = _aiken_baseline_clean(contracts_dir)
    if not baseline_ok:
        return {
            "ok": True,
            "skipped_reason": baseline_reason,
            "stdout": "",
            "stderr": "",
            "returncode": 0,
        }

    out_file = contracts_dir / "lib" / "aegis" / "_fuzz_generated.ak"
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(test_source, encoding="utf-8")

    try:
        proc = subprocess.run(
            [
                "aiken",
                "check",
                str(contracts_dir),
                "-m",
                match_filter,
            ],
            capture_output=True,
            text=True,
            timeout=timeout_s,
        )
    except FileNotFoundError:
        return {
            "ok": True,
            "skipped_reason": "aiken binary not on PATH",
            "stdout": "",
            "stderr": "",
            "returncode": 0,
        }
    except subprocess.TimeoutExpired:
        return {
            "ok": False,
            "skipped_reason": None,
            "stdout": "",
            "stderr": f"aiken check timed out after {timeout_s}s",
            "returncode": -1,
        }
    finally:
        # Always clean up the generated module so a future
        # `aiken build` from a developer doesn't see stale tests.
        try:
            out_file.unlink()
        except OSError:
            pass

    return {
        "ok": proc.returncode == 0,
        "skipped_reason": None,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
        "returncode": proc.returncode,
    }


def fuzz_pair_with_aiken(
    branch: str,
    property_name: str,
    n: int,
    seed_base: int = 1,
    aiken_match_filter: str = "fuzz_",
    contracts_dir: Path = CONTRACTS_DIR,
) -> FuzzReport:
    """Tier 1 + Tier 2.

    Generates N samples, evaluates Tier-1 concretely, and for the
    samples that have an Aiken-mapped predicate also runs them through
    `aiken check --match-tests fuzz_*`.

    Aiken-side disagreements are reported on the FuzzReport's
    `aiken_subprocess_result` field; Tier-1 disagreements remain on
    `disagreements`. The differential test asserts BOTH are empty.
    """
    report = fuzz_pair(branch, property_name, n, seed_base=seed_base)
    if not report.aiken_inputs:
        return report

    src = emit_aiken_test_module(report.aiken_inputs)
    aiken_result = _run_aiken(
        src, aiken_match_filter, contracts_dir=contracts_dir
    )
    report.aiken_subprocess_result = aiken_result
    return report
